server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka/


# 项目的安全验证
security:
  user:
    name: admin
    password: admin
    role: SUPERUSER