#服务注册中心端口号
server:
  port: 8761

eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: node1
    #将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    prefer-ip-address: true
  client:
    #是否向服务注册中心注册自己,在默认配置下，Eureka Server会将自己也作为客户端来尝试注册自己，我们需要禁用它。
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    serviceUrl:
      defaultZone: http://node2:8762/eureka/,http://node3:8763/eureka/
  server:
    #关闭自我保护机制，是否将注册中心将不可用的实例删除
    enable-self-preservation: false
    # 每隔10s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 10000