server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  registerWithEureka: true
  fetchRegistry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-hi